Make gem monkey-patch gem instead of trying to implement ChefDK CLI stuff
qubitrenegade/galvanize pull request #7
Opened 2019-05-12 06:56 UTC by qubitrenegade

This commit eschews the copy/paste of ChefDK to the `Galvanize` namespace for monkey-patching only the things we want to change in `ChefDK`.

2019-05-12 20:13 UTC, parafox0417 commented on galvanize.gemspec
> +  # spec.description   = IO.read(File.join(File.dirname(__FILE__), 'README.md'))
Did you mean to uncomment this also?  Do you need a way to parse the markdown first?  Personally I'd be OK with the markdown showing up in the description, but I'm not familiar with conventions in this area.

2019-05-12 20:17 UTC, neodon requested changes

2019-05-12 20:17 UTC, neodon commented on galvanize.gemspec
> +  # spec.description   = IO.read(File.join(File.dirname(__FILE__), 'README.md'))
Did you mean to uncomment this also?  Do you need a way to parse the markdown first?  Personally I'd be OK with the markdown showing up in the description, but I'm not familiar with conventions in this area.

2019-05-13 05:03 UTC, qubitrenegade commented on galvanize.gemspec
> +  # spec.description   = IO.read(File.join(File.dirname(__FILE__), 'README.md'))
Apparently Rubygems doesn't understand the markdown, so it showed up as a giant blob of mess.  So either need a way to translate the markdown first, or maybe just come up with a "short description" that's longer than the summary?

Seems Rubygems just uses the summary if the description isn't defined.

2019-05-13 12:40 UTC, neodon approved these changes

2019-05-14 06:52 UTC, merged